name: install-test

on:
  push

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ocaml-version:
          - 4.12.0
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - name: Install
        run: opam install . -t
